dataset:
  path: './datasets/amass_up3d_3dpw_train.npz'
<<<<<<< HEAD
  texture_path: './datasets/smpl_train_textures.npz'
  background_path: './datasets/train_files/lsun_backgrounds/train'
=======
>>>>>>> 3c27d33b631e7063f55844bab34aa02b94b5fea6
network:
  name: resnet18

  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  fine_tune_from: 'resnet-18_40-epochs'

  projection_head:
    mlp_hidden_size: 512
    projection_size: 128

data_transforms:
  s: 1
  input_shape: (256,256,18)

trainer:
<<<<<<< HEAD
  batch_size: 256
=======
  batch_size: 16
>>>>>>> 3c27d33b631e7063f55844bab34aa02b94b5fea6
  m: 0.996 # momentum update
  checkpoint_interval: 5000
  max_epochs: 40
  num_workers: 4
  input_size: 256

optimizer:
  params:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0004
